//! Cross-implementation interop tests against fixtures generated by the
//! vendored ruby-paseto reference (see tests/vectors-interop/PROVENANCE.md).
//!
//! The official vector suite proves conformance to frozen spec inputs; these
//! fixtures prove fresh tokens from another live implementation parse,
//! authenticate, and decrypt with this library — and that key IDs computed
//! here match the reference byte-for-byte.

const std = @import("std");
const paseto = @import("paseto");

const fixtures_raw = @embedFile("vectors-interop/ruby-paseto.json");

const InteropError = error{InteropFailed};

fn hexToArr(hex: []const u8, comptime N: usize) ![N]u8 {
    if (hex.len != N * 2) return InteropError.InteropFailed;
    var out: [N]u8 = undefined;
    _ = std.fmt.hexToBytes(&out, hex) catch return InteropError.InteropFailed;
    return out;
}

fn expectField(obj: std.json.ObjectMap, key: []const u8) ![]const u8 {
    return (obj.get(key) orelse return InteropError.InteropFailed).string;
}

test "ruby-paseto interop fixtures" {
    const allocator = std.testing.allocator;

    var parsed = try std.json.parseFromSlice(std.json.Value, allocator, fixtures_raw, .{});
    defer parsed.deinit();

    const cases = parsed.value.object.get("cases").?.array;
    try std.testing.expect(cases.items.len >= 36);

    var seen_local: usize = 0;
    var seen_public: usize = 0;
    for (cases.items) |case_val| {
        const c = case_val.object;
        const name = try expectField(c, "name");
        const token = try expectField(c, "token");
        const plaintext = try expectField(c, "plaintext");
        const footer = try expectField(c, "footer");
        const implicit_assertion = try expectField(c, "implicit_assertion");
        const version = try expectField(c, "version");
        const purpose = try expectField(c, "purpose");

        if (std.mem.eql(u8, purpose, "local")) {
            try runLocalCase(allocator, name, c, token, plaintext, footer, implicit_assertion, version);
            seen_local += 1;
        } else if (std.mem.eql(u8, purpose, "public")) {
            try runPublicCase(allocator, name, c, token, plaintext, footer, implicit_assertion, version);
            seen_public += 1;
        } else {
            return InteropError.InteropFailed;
        }

        try runConfusionNegatives(allocator, token, version, purpose);
    }

    try std.testing.expect(seen_local >= 24);
    try std.testing.expect(seen_public >= 12);
}

fn runLocalCase(
    allocator: std.mem.Allocator,
    name: []const u8,
    c: std.json.ObjectMap,
    token: []const u8,
    plaintext: []const u8,
    footer: []const u8,
    implicit_assertion: []const u8,
    version: []const u8,
) !void {
    const key_hex = try expectField(c, "key_hex");
    const paserk = try expectField(c, "paserk");
    const lid = try expectField(c, "lid");

    var out: []u8 = undefined;
    if (std.mem.eql(u8, version, "v4")) {
        const key_bytes = try hexToArr(key_hex, 32);
        const key = try paseto.v4.Local.fromBytes(&key_bytes);

        out = try key.decrypt(allocator, token, implicit_assertion);
        defer util_secureFree(allocator, out);
        try expectEql(name, plaintext, out);

        var result = try key.decryptWithFooter(allocator, token, implicit_assertion);
        defer result.deinit();
        try expectEql(name, plaintext, result.claims_bytes);
        try expectEql(name, footer, result.footer);

        // PASERK string round-trips into the same key, and the kX.lid we
        // derive matches the reference's byte-for-byte.
        const reparsed = try paseto.v4.Local.fromPaserk(allocator, paserk);
        try std.testing.expect(key.eql(reparsed));
        const our_lid = try key.lid();
        const our_lid_str = try our_lid.toString(allocator);
        defer allocator.free(our_lid_str);
        try expectEql(name, lid, our_lid_str);
        try std.testing.expect(our_lid.eql(try paseto.paserk.Id.parse(lid)));
    } else {
        const key_bytes = try hexToArr(key_hex, 32);
        const key = try paseto.v3.Local.fromBytes(&key_bytes);

        out = try key.decrypt(allocator, token, implicit_assertion);
        defer util_secureFree(allocator, out);
        try expectEql(name, plaintext, out);

        var result = try key.decryptWithFooter(allocator, token, implicit_assertion);
        defer result.deinit();
        try expectEql(name, plaintext, result.claims_bytes);
        try expectEql(name, footer, result.footer);

        const reparsed = try paseto.v3.Local.fromPaserk(allocator, paserk);
        try std.testing.expect(key.eql(reparsed));
        const our_lid = try key.lid();
        const our_lid_str = try our_lid.toString(allocator);
        defer allocator.free(our_lid_str);
        try expectEql(name, lid, our_lid_str);
        try std.testing.expect(our_lid.eql(try paseto.paserk.Id.parse(lid)));
    }
}

fn runPublicCase(
    allocator: std.mem.Allocator,
    name: []const u8,
    c: std.json.ObjectMap,
    token: []const u8,
    plaintext: []const u8,
    footer: []const u8,
    implicit_assertion: []const u8,
    version: []const u8,
) !void {
    const public_hex = try expectField(c, "public_hex");
    const pid = try expectField(c, "pid");

    if (std.mem.eql(u8, version, "v4")) {
        const seed_hex = try expectField(c, "seed_hex");
        const sid = try expectField(c, "sid");

        const seed = try hexToArr(seed_hex, 32);
        const signer = try paseto.v4.Public.fromSeed(&seed);
        const verifier = try paseto.v4.Public.fromPublicKeyBytes(&signer.publicKeyBytes());

        const out = try verifier.verify(allocator, token, implicit_assertion);
        defer util_secureFree(allocator, out);
        try expectEql(name, plaintext, out);

        var result = try verifier.verifyWithFooter(allocator, token, implicit_assertion);
        defer result.deinit();
        try expectEql(name, plaintext, result.claims_bytes);
        try expectEql(name, footer, result.footer);

        const pub_hex_buf = std.fmt.bytesToHex(signer.publicKeyBytes(), .lower);
        try expectEql(name, public_hex, &pub_hex_buf);

        const our_sid = try signer.sid();
        const our_sid_str = try our_sid.toString(allocator);
        defer allocator.free(our_sid_str);
        try expectEql(name, sid, our_sid_str);

        const our_pid = try signer.pid();
        const our_pid_str = try our_pid.toString(allocator);
        defer allocator.free(our_pid_str);
        try expectEql(name, pid, our_pid_str);
    } else {
        const scalar_hex = try expectField(c, "scalar_hex");

        const scalar = try hexToArr(scalar_hex, 48);
        const signer = try paseto.v3.Public.fromScalarBytes(&scalar);
        const public_bytes = try paseto.util.hexDecodeAlloc(allocator, public_hex);
        defer paseto.util.secureFree(allocator, public_bytes);
        const verifier = try paseto.v3.Public.fromPublicBytes(public_bytes);

        const out = try verifier.verify(allocator, token, implicit_assertion);
        defer util_secureFree(allocator, out);
        try expectEql(name, plaintext, out);

        var result = try verifier.verifyWithFooter(allocator, token, implicit_assertion);
        defer result.deinit();
        try expectEql(name, plaintext, result.claims_bytes);
        try expectEql(name, footer, result.footer);

        const our_pid = try signer.pid();
        const our_pid_str = try our_pid.toString(allocator);
        defer allocator.free(our_pid_str);
        try expectEql(name, pid, our_pid_str);
    }
}

/// Every fixture token must be rejected by the entry points of the other
/// version/purpose combinations — a real foreign token, not a hand-crafted
/// one, in the confusion matrix.
fn runConfusionNegatives(
    allocator: std.mem.Allocator,
    token: []const u8,
    version: []const u8,
    purpose: []const u8,
) !void {
    const v4_seed: [32]u8 = @splat(0x63);
    const v4_public = try paseto.v4.Public.fromSeed(&v4_seed);
    const v4_local = try paseto.v4.Local.fromBytes(&v4_seed);

    const v3_key: [32]u8 = @splat(0x63);
    const v3_scalar: [48]u8 = @splat(0x63);
    const v3_public = try paseto.v3.Public.fromScalarBytes(&v3_scalar);
    const v3_local = try paseto.v3.Local.fromBytes(&v3_key);

    const is_v4 = std.mem.eql(u8, version, "v4");
    const is_local = std.mem.eql(u8, purpose, "local");

    // Same version, wrong purpose.
    if (is_local) {
        if (is_v4) {
            try std.testing.expectError(paseto.Error.WrongPurpose, v4_public.verify(allocator, token, ""));
        } else {
            try std.testing.expectError(paseto.Error.WrongPurpose, v3_public.verify(allocator, token, ""));
        }
    } else {
        if (is_v4) {
            try std.testing.expectError(paseto.Error.WrongPurpose, v4_local.decrypt(allocator, token, ""));
        } else {
            try std.testing.expectError(paseto.Error.WrongPurpose, v3_local.decrypt(allocator, token, ""));
        }
    }

    // Wrong version, same and different purpose. The token cipher layer
    // folds any header mismatch into WrongPurpose (WrongVersion is surfaced
    // by the PASERK constructors); the guarantee under test is rejection.
    if (is_v4) {
        try std.testing.expectError(paseto.Error.WrongPurpose, v3_local.decrypt(allocator, token, ""));
        try std.testing.expectError(paseto.Error.WrongPurpose, v3_public.verify(allocator, token, ""));
    } else {
        try std.testing.expectError(paseto.Error.WrongPurpose, v4_local.decrypt(allocator, token, ""));
        try std.testing.expectError(paseto.Error.WrongPurpose, v4_public.verify(allocator, token, ""));
    }
}

fn expectEql(name: []const u8, expected: []const u8, actual: []const u8) !void {
    std.testing.expectEqualStrings(expected, actual) catch |err| {
        std.debug.print("interop case {s}: mismatch\n", .{name});
        return err;
    };
}

fn util_secureFree(allocator: std.mem.Allocator, buf: []u8) void {
    paseto.util.secureFree(allocator, buf);
}
