//! Shared helpers for the fuzz suite under `tests/fuzz/`.
//!
//! Everything here is fuzz/test-only. Keep it allocation-explicit, bounded,
//! and free of module-level state so every harness can `@import` it safely.

const std = @import("std");
const paseto = @import("paseto");

/// Default upper bound on Smith-generated byte strings per harness input.
pub const max_input_bytes: usize = 4096;

/// Upper bound on generated raw key material (PIE ptks, PBKW ptks, PASERK
/// raw bytes). Real keys are at most 64 bytes, but the harness may feed
/// slightly oversized garbage to exercise validation.
pub const max_key_material_bytes: usize = 128;

/// Argon2 parameter set intentionally sized for fuzz-mode throughput. The
/// production codepath uses far larger memlimit/opslimit values. These match
/// the PASERK spec minimums (memlimit divisible by 1 KiB, opslimit > 0).
pub const PbkwV4FuzzParams: paseto.paserk.pbkw.V4Params = .{
    .memlimit_bytes = 8192,
    .opslimit = 1,
    .para = 1,
};

pub const PbkwV3FuzzParams: paseto.paserk.pbkw.V3Params = .{ .iterations = 1000 };

/// Which semantic field of a token to perturb. `extra_segment` appends an
/// unexpected trailing segment to produce an over-segmented token.
pub const MutationClass = enum {
    header_byte,
    payload_byte,
    footer_byte,
    authenticator_byte,
    extra_segment,
};

pub const token_mutation_classes = [_]MutationClass{
    .header_byte,
    .payload_byte,
    .footer_byte,
    .authenticator_byte,
    .extra_segment,
};

pub fn pickMutation(s: *std.testing.Smith) MutationClass {
    return s.value(MutationClass);
}

/// Returns an allocator-owned mutated token. Round-trips through
/// `token.parse` and `token.serialize` for field-level mutations so the
/// encoded bytes stay base64-legal; header and trailing-segment mutations
/// operate directly on the serialized string.
///
/// The caller owns the returned buffer in all cases, including when parsing
/// the input fails (we fall back to a raw byte flip so the caller always
/// gets a fresh allocation).
pub fn mutateToken(
    allocator: std.mem.Allocator,
    token_str: []const u8,
    class: MutationClass,
    s: *std.testing.Smith,
) ![]u8 {
    switch (class) {
        .header_byte => {
            if (token_str.len == 0) return try allocator.dupe(u8, token_str);
            const out = try allocator.dupe(u8, token_str);
            errdefer allocator.free(out);
            const limit: u64 = @min(@as(u64, token_str.len), 9);
            const idx = s.valueRangeLessThan(u64, 0, limit);
            out[@intCast(idx)] ^= 0xff;
            return out;
        },
        .extra_segment => {
            const suffix = ".Zm9v";
            const out = try allocator.alloc(u8, token_str.len + suffix.len);
            errdefer allocator.free(out);
            @memcpy(out[0..token_str.len], token_str);
            @memcpy(out[token_str.len..], suffix);
            return out;
        },
        .payload_byte, .footer_byte, .authenticator_byte => {
            var tok = paseto.token.parse(allocator, token_str) catch {
                return rawFlip(allocator, token_str, s);
            };
            defer tok.deinit();
            const tag_len = tagLen(tok.version, tok.purpose);
            switch (class) {
                .payload_byte => {
                    const limit: u64 = if (tok.payload.len > tag_len)
                        @intCast(tok.payload.len - tag_len)
                    else
                        @intCast(tok.payload.len);
                    if (limit > 0) {
                        const idx = s.valueRangeLessThan(u64, 0, limit);
                        tok.payload[@intCast(idx)] ^= 0xff;
                    }
                },
                .authenticator_byte => {
                    if (tok.payload.len >= tag_len and tag_len > 0) {
                        const offset = tok.payload.len - tag_len;
                        const idx_in_tag = s.valueRangeLessThan(u64, 0, @intCast(tag_len));
                        tok.payload[offset + @as(usize, @intCast(idx_in_tag))] ^= 0xff;
                    } else if (tok.payload.len > 0) {
                        const idx = s.valueRangeLessThan(u64, 0, @intCast(tok.payload.len));
                        tok.payload[@intCast(idx)] ^= 0xff;
                    }
                },
                .footer_byte => {
                    if (tok.footer.len > 0) {
                        const idx = s.valueRangeLessThan(u64, 0, @intCast(tok.footer.len));
                        tok.footer[@intCast(idx)] ^= 0xff;
                    } else if (tok.payload.len > 0) {
                        const idx = s.valueRangeLessThan(u64, 0, @intCast(tok.payload.len));
                        tok.payload[@intCast(idx)] ^= 0xff;
                    }
                },
                else => unreachable,
            }
            return try paseto.token.serialize(allocator, tok.version, tok.purpose, tok.payload, tok.footer);
        },
    }
}

fn rawFlip(allocator: std.mem.Allocator, token_str: []const u8, s: *std.testing.Smith) ![]u8 {
    const out = try allocator.dupe(u8, token_str);
    errdefer allocator.free(out);
    if (token_str.len == 0) return out;
    const idx = s.valueRangeLessThan(u64, 0, @intCast(token_str.len));
    out[@intCast(idx)] ^= 0xff;
    return out;
}

fn tagLen(version: paseto.Version, purpose: paseto.Purpose) usize {
    return switch (version) {
        .v3 => switch (purpose) {
            .local => 48,
            .public => 96,
        },
        .v4 => switch (purpose) {
            .local => 32,
            .public => 64,
        },
    };
}

/// Returns void if `err` is in the allowed set, otherwise returns a sentinel
/// error so the harness reports an unexpected-error crash. Print is not
/// gated — the fuzz runner captures stderr for triage.
pub fn expectAllowed(err: anyerror, allowed: []const paseto.Error) !void {
    for (allowed) |a| if (err == a) return;
    std.debug.print("unexpected fuzz error: {t}\n", .{err});
    return error.UnexpectedFuzzError;
}

/// Convenience: the subset of errors any token-shaped parser is allowed to
/// emit. Used by multiple harnesses that consume external PASETO strings.
pub const token_parse_errors = [_]paseto.Error{
    error.InvalidToken,
    error.UnsupportedVersion,
    error.UnsupportedPurpose,
    error.InvalidBase64,
    error.InvalidPadding,
};

/// Shared allowlist for `v3.Local.decrypt` / `v4.Local.decrypt` and the
/// mutation-reject checks that exercise the same boundary.
pub const local_decrypt_errors = [_]paseto.Error{
    error.InvalidToken,
    error.WrongPurpose,
    error.InvalidAuthenticator,
    error.MessageTooShort,
    error.InvalidKey,
    error.InvalidBase64,
    error.InvalidPadding,
    error.UnsupportedVersion,
    error.UnsupportedPurpose,
    error.OutOfMemory,
};

/// Shared allowlist for `v3.Public.verify` / `v4.Public.verify` and the
/// associated mutation-reject checks.
pub const public_verify_errors = [_]paseto.Error{
    error.InvalidToken,
    error.WrongPurpose,
    error.InvalidSignature,
    error.InvalidKey,
    error.InvalidKeyPair,
    error.MessageTooShort,
    error.InvalidBase64,
    error.InvalidPadding,
    error.UnsupportedVersion,
    error.UnsupportedPurpose,
    error.OutOfMemory,
};

/// Shared constructor contract for v3/v4 public-key entrypoints that accept
/// arbitrary byte material.
pub const public_ctor_errors = [_]paseto.Error{
    error.InvalidKey,
    error.InvalidKeyPair,
    error.OutOfMemory,
};

/// Mutates a PASERK body byte while preserving the textual prefix. Returns an
/// allocator-owned duplicate; if there is no body byte to mutate yet, the
/// duplicate is returned unchanged so the caller can treat it as a no-op case.
pub fn mutatePaserkBody(
    allocator: std.mem.Allocator,
    value: []const u8,
    prefix: []const u8,
    s: *std.testing.Smith,
) ![]u8 {
    const out = try allocator.dupe(u8, value);
    errdefer allocator.free(out);
    if (!std.mem.startsWith(u8, out, prefix) or out.len <= prefix.len) return out;
    const idx = s.valueRangeLessThan(u64, @intCast(prefix.len), @intCast(out.len));
    out[@intCast(idx)] ^= 0xff;
    return out;
}
